fix: cargo fmt, cargo test, Set MSRV to 1.85.0 (#878)
* cargo fmt

This fixes the CI error:

https://github.com/XAMPPRocky/octocrab/actions/runs/24983151466/job/73149888888#step:4:13

* chore: Restore MSRV to 1.85.0, for passing CI

This fixes the CI error:

https://github.com/maflcko/octocrab/actions/runs/24987243681/job/73163540500#step:6:243

```
error: rustc 1.94.1 is not supported by the following packages:
  octocrab@0.49.9 requires rustc 1.95.0
```

* fix cargo test

This fixes the error https://github.com/XAMPPRocky/octocrab/actions/runs/24983206405/job/73150064194#step:8:1125

```
failures:

---- src/api/repos.rs - api::repos::RepoHandler<'octo>::generate (line 659) stdout ----
error[E0308]: mismatched types
   --> src/api/repos.rs:663:1
    |
663 | / octocrab::instance()
664 | |     .repos("owner", "repo")
665 | |     .generate("rust")
666 | |     .owner("new_owner")
...   |
670 | |     .send()
671 | |     .await
    | |__________^ expected `Result<(), Error>`, found `Result<Repository, Error>`
    |
    = note: expected enum `Result<(), _>`
               found enum `Result<octocrab::models::Repository, _>`

error: aborting due to 1 previous error
```

---------

Co-authored-by: MarcoFalke <*~=`'#}+{/-|&$^_@721217.xyz>